import type { ResumeData, SkillEntry } from '@/types/resume';

function createSkill(id: string, label: string, category?: string): SkillEntry {
  return category ? { id, label, category } : { id, label };
}

export const DEFAULT_RESUME_DATA: ResumeData = {
  personalInfo: {
    name: 'GAD BADR SAAD SANAD',
    title: 'SOFTWARE ENGINEER',
    email: 'gad.elhak23@gmail.com',
    phones: ['+201559660120', '+201157755120'],
    location: 'Mansoura, EGYPT',
    links: [
      { label: 'Upwork', url: 'https://www.upwork.com/freelancers/~0151601b9d233db4b8' },
      { label: 'LinkedIn', url: 'https://linkedin.com/in/gad-badr-583060208/' },
      { label: 'GitHub', url: 'https://github.com/DevGadBadr' },
    ],
  },
  about:
    'Professional Developer and Engineer always seeking to excel and advance in the technology field. Combining Electrical Engineering background with strong software development skills to build reliable, automated, and data-driven systems.',
  experience: [
    {
      id: '1',
      role: 'Web Developer',
      roleSubtitle: '+3 Year Freelancer for Automation and Web Projects',
      company: 'Upwork',
      period: '03/2023 – Ongoing',
      bullets: [
        'Built a web-based Automation tool for Clinics patients data matching, PDF reports generation and posting to ClickUp. Mainly used React and Nest frameworks.',
        'Built a web-based automation tool using React / Nest / Playwright to automate managing bulk Amazon account settings.',
        'More than three years of coding experience using Python and JS.',
        'Adhering to programming best practices and clean coding.',
        'Designing, building and coding applications from scratch.',
        'Software engineering and systems design.',
      ],
    },
    {
      id: '2',
      role: 'Electrical Engineer',
      roleSubtitle: '+4 Years of Practical Experience as Engineer',
      company: 'MADKOUR Technology',
      period: '11/2020 – Ongoing',
      bullets: [
        'Developing Automation/SCADA for agricultural/electrical projects.',
        'Teamwork and engaging in successful project completion.',
        'Working with ERP Systems for reports and business management.',
      ],
    },
  ],
  projects: [
    {
      id: '1',
      title: 'Web Based SCADA Platform',
      description: 'Using React and Express APIs with JavaScript / Python / CSS',
      bullets: [
        'Used ReactJs framework to build the front-end with responsive design and modern UI from scratch.',
        'Integrating communication protocols and APIs / Web Sockets to manage real-time data flow.',
        'Backend with Node.js/Express handling device data, alarms, and historical logs.',
      ],
      tags: ['React', 'Node.js', 'WebSockets', 'Python', 'CSS'],
    },
    {
      id: '2',
      title: 'Clinic Automation Tool',
      description: 'React / NestJS / PDF generation / ClickUp API',
      bullets: [
        'Automated patient data matching from multiple sources into structured PDF reports.',
        'Integrated ClickUp API to post and manage tasks directly from the web interface.',
        'Reduced manual clinic data entry time by over 80%.',
      ],
      tags: ['React', 'NestJS', 'Puppeteer', 'ClickUp API'],
      deployment: {
        url: 'https://demo.example.com/clinic-automation',
        credentials: [
          { id: 'clinic-demo-email', label: 'Email', value: 'demo@example.com' },
          { id: 'clinic-demo-password', label: 'Password', value: 'demo_pass_2026' },
        ],
      },
    },
    {
      id: '3',
      title: 'Amazon Account Manager',
      description: 'React / Nest / Playwright — bulk account automation',
      bullets: [
        'Automated bulk account settings management for Amazon seller accounts using Playwright.',
        'Built a dashboard to queue, monitor, and log automation jobs in real time.',
      ],
      tags: ['React', 'NestJS', 'Playwright', 'Automation'],
    },
    {
      id: '4',
      title: 'Multiple Python Scripts & Tools',
      description: 'From Games to Automation Scripts',
      bullets: [
        'Mastered Python OOP, functions coding, and proper project structure.',
        'Selenium-based web scrapers and automation bots.',
        'Defined and leveraged useful Python libraries across multiple domains.',
      ],
      tags: ['Python', 'Selenium', 'PyQt', 'Automation'],
    },
  ],
  skills: [
    createSkill('skill-python', 'Python', 'Languages'),
    createSkill('skill-typescript', 'TypeScript', 'Languages'),
    createSkill('skill-javascript', 'JavaScript', 'Languages'),
    createSkill('skill-react', 'React', 'Frontend'),
    createSkill('skill-node-js', 'Node.js', 'Backend'),
    createSkill('skill-nestjs', 'NestJS', 'Backend'),
    createSkill('skill-html', 'HTML', 'Frontend'),
    createSkill('skill-css', 'CSS', 'Frontend'),
    createSkill('skill-flask', 'Flask', 'Backend'),
    createSkill('skill-next-js', 'Next.js', 'Frontend'),
    createSkill('skill-selenium', 'Selenium', 'Automation'),
    createSkill('skill-playwright', 'Playwright', 'Automation'),
    createSkill('skill-make-com', 'Make.com', 'Automation'),
    createSkill('skill-mysql', 'MySQL', 'Data'),
    createSkill('skill-postgresql', 'PostgreSQL', 'Data'),
    createSkill('skill-mongodb', 'MongoDB', 'Data'),
    createSkill('skill-docker', 'Docker', 'DevOps'),
    createSkill('skill-devops', 'DevOps', 'DevOps'),
    createSkill('skill-aws', 'AWS', 'Cloud'),
    createSkill('skill-google-cloud', 'Google Cloud', 'Cloud'),
    createSkill('skill-ubuntu', 'Ubuntu', 'DevOps'),
    createSkill('skill-ssh', 'SSH', 'DevOps'),
    createSkill('skill-git', 'GIT', 'Tools'),
    createSkill('skill-vscode', 'VSCode', 'Tools'),
    createSkill('skill-scada', 'SCADA', 'Automation'),
    createSkill('skill-ignition', 'Ignition', 'Automation'),
    createSkill('skill-web-sockets', 'Web Sockets', 'Backend'),
    createSkill('skill-apis', 'APIs', 'Backend'),
    createSkill('skill-pyqt', 'PyQt', 'Desktop'),
    createSkill('skill-inkscape', 'Inkscape', 'Tools'),
    createSkill('skill-winscp', 'WinSCP', 'Tools'),
    createSkill('skill-putty', 'Putty', 'Tools'),
    createSkill('skill-engineering', 'Engineering', 'Engineering'),
    createSkill('skill-web-development', 'Web Development', 'Frontend'),
  ],
  education: [
    {
      id: '1',
      degree: 'BSc. Degree in Electrical Engineering',
      institution: 'Mansoura University',
      period: 'Sept 2015 – June 2020',
    },
    {
      id: '2',
      degree: 'M.Sc. in Solar Power Systems Optimization with AI',
      institution: 'Mansoura University',
      period: 'Sept 2021 – Ongoing',
    },
  ],
  certificates: [
    {
      id: '1',
      title: 'Python Programming',
      issuer: 'Udemy',
      date: 'May 16, 2023',
      hours: '40 Hours',
      link: 'https://www.udemy.com/certificate/example',
    },
    {
      id: '2',
      title: 'Advanced Web Development',
      issuer: 'Udemy',
      date: 'July 18, 2025',
    },
  ],
  activeTemplateId: 'default',
  templates: [
    {
      id: 'default',
      name: 'Default Resume',
      hideContactInfo: false,
      selected: {
        experienceIds: ['1', '2'],
        projectIds: ['1', '2', '3', '4'],
        skillIds: [
          'skill-python',
          'skill-typescript',
          'skill-javascript',
          'skill-react',
          'skill-node-js',
          'skill-nestjs',
          'skill-html',
          'skill-css',
          'skill-flask',
          'skill-next-js',
          'skill-selenium',
          'skill-playwright',
          'skill-make-com',
          'skill-mysql',
          'skill-postgresql',
          'skill-mongodb',
          'skill-docker',
          'skill-devops',
          'skill-aws',
          'skill-google-cloud',
          'skill-ubuntu',
          'skill-ssh',
          'skill-git',
          'skill-vscode',
          'skill-scada',
          'skill-ignition',
          'skill-web-sockets',
          'skill-apis',
          'skill-pyqt',
          'skill-inkscape',
          'skill-winscp',
          'skill-putty',
          'skill-engineering',
          'skill-web-development',
        ],
        educationIds: ['1', '2'],
        certificateIds: ['1', '2'],
      },
    },
    {
      id: 'upwork',
      name: 'Upwork Resume',
      hideContactInfo: true,
      selected: {
        experienceIds: ['1', '2'],
        projectIds: ['1', '2', '3', '4'],
        skillIds: [
          'skill-python',
          'skill-typescript',
          'skill-javascript',
          'skill-react',
          'skill-node-js',
          'skill-nestjs',
          'skill-selenium',
          'skill-playwright',
          'skill-mongodb',
          'skill-docker',
          'skill-apis',
          'skill-web-development',
        ],
        educationIds: ['1', '2'],
        certificateIds: ['1', '2'],
      },
    },
  ],
};
