version: '3.9'
services:
  mongodb:
    image: mongo:7.0
    container_name: resume-mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: resume
      MONGO_INITDB_ROOT_USERNAME: devgadbadr
      MONGO_INITDB_ROOT_PASSWORD: gogoMongoDB2026
volumes:
  mongo_data:
    driver: local